.gitignore, README.md, examples/README.md, examples/pom.xml, examples/src/main/java/io/numaproj/numaflow/examples/function/forward/ForwardFunction.java, examples/src/main/java/io/numaproj/numaflow/examples/sink/simple/SimpleSink.java, pom.xml, src/main/java/io/numaproj/numaflow/function/Function.java, src/main/java/io/numaproj/numaflow/function/FunctionServer.java, src/main/java/io/numaproj/numaflow/function/FunctionService.java, src/main/java/io/numaproj/numaflow/function/MapFunc.java, src/main/java/io/numaproj/numaflow/function/MapHandler.java, src/main/java/io/numaproj/numaflow/function/Message.java, src/main/java/io/numaproj/numaflow/sink/Response.java, src/main/java/io/numaproj/numaflow/sink/Sink.java, src/main/java/io/numaproj/numaflow/sink/SinkFunc.java, src/main/java/io/numaproj/numaflow/sink/SinkHandler.java, src/main/java/io/numaproj/numaflow/sink/SinkServer.java, src/main/java/io/numaproj/numaflow/sink/SinkService.java, src/main/proto/function/v1/udfunction.proto, src/main/proto/sink/v1/udsink.proto, src/test/java/io/numaproj/numaflow/function/FunctionServerTest.java, src/test/java/io/numaproj/numaflow/sink/SinkServerTest.java
Signed-off-by: David Seapy <dseapy@gmail.com>
=> chore: initial code

README.md, examples/src/main/java/io/numaproj/numaflow/examples/function/sum/SumFunction.java, examples/src/main/java/io/numaproj/numaflow/examples/sink/simple/SimpleSink.java, src/main/java/io/numaproj/numaflow/function/FunctionServer.java, src/main/java/io/numaproj/numaflow/function/FunctionService.java, src/main/java/io/numaproj/numaflow/function/reduce/ReduceDatumStream.java, src/main/java/io/numaproj/numaflow/function/reduce/ReduceDatumStreamImpl.java, src/main/java/io/numaproj/numaflow/sink/SinkDatumStream.java, src/main/java/io/numaproj/numaflow/sink/SinkDatumStreamImpl.java, src/main/java/io/numaproj/numaflow/sink/SinkFunc.java, src/main/java/io/numaproj/numaflow/sink/SinkHandler.java, src/main/java/io/numaproj/numaflow/sink/SinkServer.java, src/main/java/io/numaproj/numaflow/sink/SinkService.java, src/main/proto/sink/v1/udsink.proto, src/test/java/io/numaproj/numaflow/function/FunctionServerTest.java, src/test/java/io/numaproj/numaflow/function/ReduceOutputStreamObserver.java, src/test/java/io/numaproj/numaflow/sink/SinkOutputStreamObserver.java, src/test/java/io/numaproj/numaflow/sink/SinkServerTest.java
Signed-off-by: Yashash H L <yashashhl25@gmail.com>
https://github.com/numaproj/numaflow/issues/335
=> udsink with streaming

examples/src/main/java/io/numaproj/numaflow/examples/function/evenodd/Forward.java, examples/src/main/java/io/numaproj/numaflow/examples/function/flatmap/FlatMap.java, examples/src/main/java/io/numaproj/numaflow/examples/function/forward/ForwardFunction.java, examples/src/main/java/io/numaproj/numaflow/examples/function/sum/SumFunction.java, examples/src/main/java/io/numaproj/numaflow/examples/sink/simple/SimpleSink.java, pom.xml, src/main/java/io/numaproj/numaflow/function/Datum.java, src/main/java/io/numaproj/numaflow/function/FunctionService.java, src/main/java/io/numaproj/numaflow/function/HandlerDatum.java, src/main/java/io/numaproj/numaflow/function/map/MapFunc.java, src/main/java/io/numaproj/numaflow/function/map/MapHandler.java, src/main/java/io/numaproj/numaflow/function/reduce/ReduceDatumStream.java, src/main/java/io/numaproj/numaflow/function/reduce/ReduceDatumStreamImpl.java, src/main/java/io/numaproj/numaflow/sink/Datum.java, src/main/java/io/numaproj/numaflow/sink/HandlerDatum.java, src/main/java/io/numaproj/numaflow/sink/SinkDatumStream.java, src/main/java/io/numaproj/numaflow/sink/SinkDatumStreamImpl.java, src/main/java/io/numaproj/numaflow/sink/SinkService.java, src/test/java/io/numaproj/numaflow/function/FunctionServerTest.java, src/test/java/io/numaproj/numaflow/sink/SinkServerTest.java
Signed-off-by: Yashash H L <yashashhl25@gmail.com>
=> using one gRPC stream per window

.editorconfig, .github/workflows/CODEOWNERS, README.md, examples/pom.xml, examples/src/main/java/io/numaproj/numaflow/examples/function/evenodd/EvenOddFunction.java, examples/src/main/java/io/numaproj/numaflow/examples/function/flatmap/FlatMapFunction.java, pom.xml, src/main/java/io/numaproj/numaflow/common/GrpcServerConfig.java, src/main/java/io/numaproj/numaflow/function/FunctionServer.java, src/main/java/io/numaproj/numaflow/function/FunctionService.java, src/main/java/io/numaproj/numaflow/function/Message.java, src/main/java/io/numaproj/numaflow/function/metadata/IntervalWindowImpl.java, src/main/java/io/numaproj/numaflow/function/metadata/MetadataImpl.java, src/main/java/io/numaproj/numaflow/function/reduce/ReduceDatumStream.java, src/main/java/io/numaproj/numaflow/function/reduce/ReduceDatumStreamImpl.java, src/main/java/io/numaproj/numaflow/function/reduce/ReduceFunc.java, src/main/java/io/numaproj/numaflow/sink/Response.java, src/main/java/io/numaproj/numaflow/sink/SinkDatumStream.java, src/main/java/io/numaproj/numaflow/sink/SinkDatumStreamImpl.java, src/main/java/io/numaproj/numaflow/sink/SinkServer.java, src/main/java/io/numaproj/numaflow/sink/SinkService.java, src/main/java/io/numaproj/numaflow/utils/TriFunction.java, src/test/java/io/numaproj/numaflow/function/FunctionServerTest.java, src/test/java/io/numaproj/numaflow/sink/SinkServerTest.java
Signed-off-by: Keran Yang <yangkr920208@gmail.com>
=> chore: rename classes and use lombok when possible

pom.xml
Please consider this revised scope for the `slf4j-simple` binding. Without this, the slf4j binding is included in the compiled scope of the SDK, making it a headache to use with any other log bindings.
> BASIC RULE Embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding/provider but only depend on slf4j-api. When a library declares a transitive dependency on a specific binding, that binding is imposed on the end-user negating the purpose of SLF4J. Note that declaring a non-transitive dependency on a binding, for example for testing, does not affect the end-user.
(ref: https://www.slf4j.org/manual.html#libraries)
Note that with this change you'll still have logging output from tests, it just simplifies consumption of the SDK:
```
[INFO] …
```
=> chore: scopes slf4j binding to test

src/main/java/io/numaproj/numaflow/function/FunctionService.java, src/main/java/io/numaproj/numaflow/function/Message.java, src/main/java/io/numaproj/numaflow/function/MessageT.java
gRPC setters doesn't accept null values, throws npe
=> chore: fix npe

examples/src/main/java/io/numaproj/numaflow/examples/function/map/eventtimefilter/EventTimeFilterFunction.java, src/main/java/io/numaproj/numaflow/function/FunctionServer.java, src/main/java/io/numaproj/numaflow/sink/SinkServer.java
update event time filter transformer to use tag for conditional forwarding.
=> fix: update event time filter transformer to use tag

src/main/java/io/numaproj/numaflow/function/types/MessageList.java, src/main/java/io/numaproj/numaflow/function/types/MessageTList.java
- We get NullPointerException when addMessages() is invoked directly using builder, fixed it by adding a null check
=> fix: npe inside message list builder

src/main/java/io/numaproj/numaflow/sourcer/Sourcer.java, src/main/proto/source/v1/source.proto
This PR is the Java version of https://github.com/numaproj/numaflow-go/pull/81
=> fix: allow returning negative value from source pending api

pom.xml
=> fix: upgrade netty to mitigate Vulnerability issue

README.md, examples/pom.xml, pom.xml
Such that it can save us some time in the future when we update the version of our e2e test images.
=> chore: add e2e image build to example pom file

src/main/java/io/numaproj/numaflow/sideinput/GRPCConfig.java, src/main/java/io/numaproj/numaflow/sideinput/Server.java, src/test/java/io/numaproj/numaflow/sideinput/GRPCConfigTest.java, src/test/java/io/numaproj/numaflow/sideinput/ServerTest.java
Implements: [Issue 1457](https://github.com/numaproj/numaflow/issues/1457) for the Java sdk
=> chore: write server info for sideinput sdk

src/main/java/io/numaproj/numaflow/info/ServerInfoAccessor.java, src/main/java/io/numaproj/numaflow/mapper/Constants.java, src/main/java/io/numaproj/numaflow/mapper/GRPCConfig.java, src/main/java/io/numaproj/numaflow/mapstreamer/Constants.java, src/main/java/io/numaproj/numaflow/mapstreamer/GRPCConfig.java, src/main/java/io/numaproj/numaflow/reducer/Constants.java, src/main/java/io/numaproj/numaflow/reducer/GRPCConfig.java, src/main/java/io/numaproj/numaflow/reducestreamer/Constants.java, src/main/java/io/numaproj/numaflow/reducestreamer/GRPCConfig.java, src/main/java/io/numaproj/numaflow/sideinput/Constants.java, src/main/java/io/numaproj/numaflow/sideinput/GRPCConfig.java, src/main/java/io/numaproj/numaflow/sinker/Constants.java, src/main/java/io/numaproj/numaflow/sinker/GRPCConfig.java, src/main/java/io/numaproj/numaflow/sourcer/Constants.java, src/main/java/io/numaproj/numaflow/sourcer/GRPCConfig.java, src/main/java/io/numaproj/numaflow/sourcetransformer/Constants.java, src/main/java/io/numaproj/numaflow/sourcetransformer/GRPCConfig.java, src/test/java/io/numaproj/numaflow/mapper/GRPCConfigTest.java, src/test/java/io/numaproj/numaflow/mapstreamer/GRPCConfigTest.java, src/test/java/io/numaproj/numaflow/reducer/GRPCConfigTest.java, src/test/java/io/numaproj/numaflow/reducestreamer/GRPCConfigTest.java, src/test/java/io/numaproj/numaflow/sideinput/GRPCConfigTest.java, src/test/java/io/numaproj/numaflow/sinker/GRPCConfigTest.java, src/test/java/io/numaproj/numaflow/sourcer/GRPCConfigTest.java, src/test/java/io/numaproj/numaflow/sourcetransformer/GRPCConfigTest.java
Implement [#1456](https://github.com/numaproj/numaflow/issues/1456) for java sdk
=> chore: add separate server info file paths for services

.github/workflows/build-push.yaml, .github/workflows/run-tests.yaml, update_examples.sh
fixes example image building issue in https://github.com/numaproj/numaflow-java/commit/f329e10d23679f01f28c99845bc595d135a7d637
=> fix: compile pom.xml before building

src/main/java/io/numaproj/numaflow/info/ServerInfo.java, src/main/java/io/numaproj/numaflow/shared/GrpcServerUtils.java, src/test/java/io/numaproj/numaflow/info/ServerInfoAccessorImplTest.java
related to: [#1504](https://github.com/numaproj/numaflow/issues/1504)
=> chore: add minimum client version to server info class

src/main/java/io/numaproj/numaflow/info/ServerInfo.java, src/main/java/io/numaproj/numaflow/shared/GrpcServerUtils.java, src/test/java/io/numaproj/numaflow/info/ServerInfoAccessorImplTest.java
https://github.com/numaproj/numaflow-python/pull/152#discussion_r1557994247
=> chore: update ServerInfo class

README.md, examples/pom.xml, pom.xml, src/main/java/io/numaproj/numaflow/shared/GrpcServerUtils.java
fixes https://github.com/numaproj/numaflow/issues/1592
=> chore: Restart if there are any uncaught exceptions.

.github/workflows/run-tests.yaml
Reference: https://app.codecov.io/github/numaproj/numaflow-java/new
Closes #123
=> test: enable displaying codecov report

README.md, examples/pom.xml, pom.xml, src/main/java/io/numaproj/numaflow/info/ServerInfo.java
Will merge after my refactor PR.
=> chore: prepare for releasing 0.9.0

pom.xml
Fix https://osv.dev/vulnerability/GHSA-735f-pc8j-v9w8
Closes #159
=> chore: upgrade protobuf-java version to fix CVE-2024-7254

pom.xml
Also fix CVEs.
Test: `mvn clean install` passed.
=> chore: upgrade some dependencies to their latest version
